/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { useAnimations } from "@react-three/drei/useAnimations";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/car.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    console.log(actions);
    actions.BodyAction.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Lowpoly_car">
          <group name="Body">
            <mesh
              name="Circle"
              castShadow
              receiveShadow
              geometry={nodes.Circle.geometry}
              material={materials["Car paint"]}
            />
            <mesh
              name="Circle_1"
              castShadow
              receiveShadow
              geometry={nodes.Circle_1.geometry}
              material={materials.Steel}
            />
            <mesh
              name="Circle_2"
              castShadow
              receiveShadow
              geometry={nodes.Circle_2.geometry}
              material={materials["Car windshield glass"]}
            />
            <mesh
              name="Circle_3"
              castShadow
              receiveShadow
              geometry={nodes.Circle_3.geometry}
              material={materials["Red glass"]}
            />
            <mesh
              name="Circle_4"
              castShadow
              receiveShadow
              geometry={nodes.Circle_4.geometry}
              material={materials.Rubber}
            />
            <mesh
              name="Circle_5"
              castShadow
              receiveShadow
              geometry={nodes.Circle_5.geometry}
              material={materials["Automotive led lights"]}
            />
            <mesh
              name="Circle_6"
              castShadow
              receiveShadow
              geometry={nodes.Circle_6.geometry}
              material={materials["Stitched Upholstery red"]}
            />
            <mesh
              name="Circle_7"
              castShadow
              receiveShadow
              geometry={nodes.Circle_7.geometry}
              material={nodes.Circle_7.material}
            />
            <mesh
              name="Circle_8"
              castShadow
              receiveShadow
              geometry={nodes.Circle_8.geometry}
              material={materials["Car rubber wheel"]}
            />
            <mesh
              name="Circle_9"
              castShadow
              receiveShadow
              geometry={nodes.Circle_9.geometry}
              material={materials.Speed}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/car.glb");
