/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { useAnimations } from "@react-three/drei/useAnimations";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/kick.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    console.log(actions);
    actions.Armada.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          material={materials.kobra_Body}
          geometry={nodes.kobra.geometry}
          skeleton={nodes.kobra.skeleton}
        />
      </group>
    </group>
    // <group ref={group} {...props} dispose={null}>
    //   <group name="Scene">
    //     <group name="main" rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
    //       <skinnedMesh
    //         name="kobra"
    //         geometry={nodes.kobra.geometry}
    //         material={materials.Ch03_Body}
    //         skeleton={nodes.kobra.skeleton}
    //       />
    //       <primitive object={nodes.mixamorigHips} />
    //     </group>
    //     <group name="main2" rotation={[Math.PI / 2, 0, 0]} scale={[0.18, 0.18, 0.18]}>
    //       <skinnedMesh
    //         name="Ch032"
    //         geometry={nodes.Ch032.geometry}
    //         material={materials["Ch03_Body.001"]}
    //         skeleton={nodes.Ch032.skeleton}
    //       />
    //       <primitive object={nodes.mixamorigHips_1} />
    //     </group>
    //   </group>
    // </group>
  );
}

useGLTF.preload("/kick.glb");
