/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { useAnimations } from "@react-three/drei/useAnimations";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/toyota.glb");
  console.log(nodes,materials)
  const { actions } = useAnimations(animations, group);
  console.log(actions)
  useEffect(() => {
    console.log(actions);
    actions.ToyotaAction.play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Toyota" scale={2.802}>
          <mesh
            name="1001"
            castShadow
            receiveShadow
            geometry={nodes["1001"].geometry}
            material={materials["glossy black"]}
            position={[0, 0, 0.744]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={0.211}
          />
          <group
            name="1002"
            position={[0, 0, 0.744]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={0.211}
          >
            <mesh
              name="1007"
              castShadow
              receiveShadow
              geometry={nodes["1007"].geometry}
              material={materials["mat mt.001"]}
            />
            <mesh
              name="1007_1"
              castShadow
              receiveShadow
              geometry={nodes["1007_1"].geometry}
              material={materials.chrome}
            />
          </group>
          <mesh
            name="1003"
            castShadow
            receiveShadow
            geometry={nodes["1003"].geometry}
            material={materials["tailight.002"]}
            position={[0, 0, 0.744]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={0.211}
          />
          <mesh
            name="brake005"
            castShadow
            receiveShadow
            geometry={nodes.brake005.geometry}
            material={materials["brake.002"]}
            position={[0.185, 0.078, -0.234]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={[0.218, 0.235, 0.243]}
          />
          <mesh
            name="brake006"
            castShadow
            receiveShadow
            geometry={nodes.brake006.geometry}
            material={materials["Material.003"]}
            position={[0.187, 0.078, -0.261]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.218, -0.243, -0.243]}
          />
          <mesh
            name="brake007"
            castShadow
            receiveShadow
            geometry={nodes.brake007.geometry}
            material={materials["brake.002"]}
            position={[-0.187, 0.078, -0.234]}
            rotation={[0, 0, -Math.PI]}
            scale={[-0.218, -0.235, -0.243]}
          />
          <mesh
            name="brake008"
            castShadow
            receiveShadow
            geometry={nodes.brake008.geometry}
            material={materials["Material.003"]}
            position={[-0.188, 0.078, -0.261]}
            scale={[0.218, 0.243, 0.243]}
          />
          <mesh
            name="Circle005"
            castShadow
            receiveShadow
            geometry={nodes.Circle005.geometry}
            material={materials["whipper rubber.001"]}
            position={[-0.145, 0.215, 0.163]}
            rotation={[1.892, 0.348, -0.127]}
            scale={0.066}
          />
          <mesh
            name="Circle006"
            castShadow
            receiveShadow
            geometry={nodes.Circle006.geometry}
            material={materials["whipper rubber.002"]}
            position={[-0.021, 0.237, 0.154]}
            rotation={[0.569, 0.24, -0.169]}
            scale={0.069}
          />
          <mesh
            name="Circle008"
            castShadow
            receiveShadow
            geometry={nodes.Circle008.geometry}
            material={materials["whipper rubber.002"]}
            position={[-0.142, 0.212, 0.164]}
            rotation={[0.544, -0.223, 0.37]}
            scale={-0.003}
          />
          <mesh
            name="Circle036"
            castShadow
            receiveShadow
            geometry={nodes.Circle036.geometry}
            material={materials["whipper rubber.002"]}
            position={[-0.012, 0.225, 0.18]}
            rotation={[1.875, 0.016, -0.318]}
            scale={0.066}
          />
          <mesh
            name="Circle037"
            castShadow
            receiveShadow
            geometry={nodes.Circle037.geometry}
            material={materials["whipper rubber.002"]}
            position={[0.104, 0.238, 0.139]}
            rotation={[0.629, 0.361, -0.307]}
            scale={0.069}
          />
          <mesh
            name="Circle039"
            castShadow
            receiveShadow
            geometry={nodes.Circle039.geometry}
            material={materials["whipper rubber.002"]}
            position={[-0.012, 0.22, 0.181]}
            rotation={[0.495, -0.032, 0.138]}
            scale={-0.003}
          />
          <group
            name="Cube"
            position={[0, 0, -0.264]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.357}
          >
            <mesh
              name="Cube009_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube009_1.geometry}
              material={materials["headlight.001"]}
            />
            <mesh
              name="Cube009_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube009_2.geometry}
              material={materials.headlight}
            />
          </group>
          <mesh
            name="Cube001"
            castShadow
            receiveShadow
            geometry={nodes.Cube001.geometry}
            material={materials["headlight.001"]}
            position={[0, 0, -0.265]}
            rotation={[0, 0, Math.PI]}
            scale={0.004}
          />
          <mesh
            name="Cube002"
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials.glass}
            position={[0, 0, -0.264]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.357}
          />
          <mesh
            name="Cube003"
            castShadow
            receiveShadow
            geometry={nodes.Cube003.geometry}
            material={materials["Mat mt.001"]}
            position={[0.087, 0.209, 0.014]}
            rotation={[-2.777, 0, Math.PI]}
            scale={-0.003}
          />
          <mesh
            name="Cube004"
            castShadow
            receiveShadow
            geometry={nodes.Cube004.geometry}
            material={materials["Mat mt.001"]}
            position={[0.087, 0.209, 0.014]}
            rotation={[-2.777, 0, Math.PI]}
            scale={-0.003}
          />
          <mesh
            name="Cube005"
            castShadow
            receiveShadow
            geometry={nodes.Cube005.geometry}
            material={materials["mat mt.001"]}
            position={[0, 0.084, 0.495]}
            scale={[0.155, 0.042, 0.024]}
          />
          <mesh
            name="Cube006"
            castShadow
            receiveShadow
            geometry={nodes.Cube006.geometry}
            material={materials.glass}
            position={[0, -0.012, -0.264]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.357}
          />
          <group name="Cube007" scale={0.006}>
            <mesh
              name="Cube007_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube007_1.geometry}
              material={materials["body.002"]}
            />
            <mesh
              name="Cube007_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube007_2.geometry}
              material={materials["mat mt"]}
            />
          </group>
          <mesh
            name="Cube008"
            castShadow
            receiveShadow
            geometry={nodes.Cube008.geometry}
            material={materials["body.002"]}
            scale={0.006}
          />
          <mesh
            name="Cube009"
            castShadow
            receiveShadow
            geometry={nodes.Cube009.geometry}
            material={materials["whipper rubber.002"]}
            position={[-0.022, 0.24, 0.157]}
            rotation={[0.637, 0.329, 0.028]}
            scale={[0.107, 0.104, 0.081]}
          />
          <mesh
            name="Cube010"
            castShadow
            receiveShadow
            geometry={nodes.Cube010.geometry}
            material={materials["whipper rubber.002"]}
            position={[-0.022, 0.235, 0.154]}
            rotation={[0.637, 0.329, 0.028]}
            scale={[0.104, 0.104, 0.15]}
          />
          <mesh
            name="Cube011"
            castShadow
            receiveShadow
            geometry={nodes.Cube011.geometry}
            material={materials["whipper rubber.002"]}
            position={[-0.135, 0.217, 0.165]}
            rotation={[0.599, 0.168, 0.126]}
            scale={0.104}
          />
          <mesh
            name="Cube012"
            castShadow
            receiveShadow
            geometry={nodes.Cube012.geometry}
            material={materials["whipper rubber.002"]}
            position={[-0.135, 0.217, 0.165]}
            rotation={[0.599, 0.168, 0.126]}
            scale={0.104}
          />
          <mesh
            name="Cube013"
            castShadow
            receiveShadow
            geometry={nodes.Cube013.geometry}
            material={materials["whipper rubber.002"]}
            position={[0.104, 0.241, 0.142]}
            rotation={[0.739, 0.362, -0.119]}
            scale={[0.107, 0.104, 0.081]}
          />
          <group
            name="Cube014"
            position={[-0.003, 0.274, 0.03]}
            rotation={[-0.118, 0, -Math.PI]}
            scale={-0.012}
          >
            <mesh
              name="Mesh_12"
              castShadow
              receiveShadow
              geometry={nodes.Mesh_12.geometry}
              material={materials["Mat MT"]}
            />
            <mesh
              name="Mesh_13"
              castShadow
              receiveShadow
              geometry={nodes.Mesh_13.geometry}
              material={materials["metal.001"]}
            />
          </group>
          <mesh
            name="Cube016"
            castShadow
            receiveShadow
            geometry={nodes.Cube016.geometry}
            material={materials["Mat mt"]}
            position={[-0.001, 0.115, 0.549]}
            scale={[-0.045, -0.014, -0.018]}
          />
          <mesh
            name="Cube019"
            castShadow
            receiveShadow
            geometry={nodes.Cube019.geometry}
            material={materials["whipper rubber.002"]}
            position={[-0.004, 0.225, 0.179]}
            rotation={[0.629, 0.361, -0.083]}
            scale={0.104}
          />
          <mesh
            name="Cube020"
            castShadow
            receiveShadow
            geometry={nodes.Cube020.geometry}
            material={materials["whipper rubber.002"]}
            position={[-0.004, 0.225, 0.18]}
            rotation={[0.629, 0.361, -0.083]}
            scale={0.104}
          />
          <mesh
            name="Cube021"
            castShadow
            receiveShadow
            geometry={nodes.Cube021.geometry}
            material={materials["whipper rubber.002"]}
            position={[0.103, 0.236, 0.138]}
            rotation={[0.739, 0.362, -0.119]}
            scale={[0.104, 0.104, 0.15]}
          />
          <mesh
            name="Cylinder"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder.geometry}
            material={materials["Mat MT"]}
            position={[-0.003, 0.281, 0.034]}
            rotation={[0.363, 0, Math.PI]}
            scale={[0.002, 0.006, 0.002]}
          />
          <mesh
            name="Cylinder001"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={materials["whipper rubber.002"]}
            position={[-0.143, 0.215, 0.165]}
            rotation={[2.19, 0.132, -0.17]}
            scale={0.333}
          />
          <mesh
            name="Cylinder002"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002.geometry}
            material={materials["shiny metal.002"]}
            position={[-0.021, 0.233, 0.158]}
            rotation={[2.269, 0.022, -0.252]}
            scale={0.333}
          />
          <mesh
            name="Cylinder004"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004.geometry}
            material={materials["whipper rubber.002"]}
            position={[-0.011, 0.223, 0.182]}
            rotation={[2.17, -0.078, -0.363]}
            scale={0.333}
          />
          <mesh
            name="Cylinder005"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder005.geometry}
            material={materials["whipper rubber.002"]}
            position={[0.104, 0.234, 0.142]}
            rotation={[2.17, -0.078, -0.363]}
            scale={0.333}
          />
          <mesh
            name="dashboard"
            castShadow
            receiveShadow
            geometry={nodes.dashboard.geometry}
            material={materials["Mat mt.001"]}
            position={[0.052, 0.195, 0.036]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={0}
          />
          <group
            name="Empty004"
            position={[-0.196, 0.078, 0.333]}
            rotation={[0, -0.611, 0]}
            scale={[0.294, 0.338, 0.338]}
          >
            <mesh
              name="brake001"
              castShadow
              receiveShadow
              geometry={nodes.brake001.geometry}
              material={materials["brake.002"]}
              position={[0.031, 0, -0.077]}
              scale={[0.741, 0.697, 0.72]}
            />
            <mesh
              name="brake002"
              castShadow
              receiveShadow
              geometry={nodes.brake002.geometry}
              material={materials["Material.003"]}
              position={[0.025, 0, 0.008]}
              scale={[0.741, 0.72, 0.72]}
            />
            <group
              name="Plane059"
              position={[0, 0.007, 0]}
              rotation={[0, 0, 0.178]}
              scale={[0.491, 0.625, 0.623]}
            >
              <mesh
                name="Plane060_1"
                castShadow
                receiveShadow
                geometry={nodes.Plane060_1.geometry}
                material={materials["Front Tire.003"]}
              />
              <mesh
                name="Plane060_2"
                castShadow
                receiveShadow
                geometry={nodes.Plane060_2.geometry}
                material={materials["Front Tire.002"]}
              />
            </group>
            <mesh
              name="Plane060"
              castShadow
              receiveShadow
              geometry={nodes.Plane060.geometry}
              material={materials.chrome}
              position={[-0.037, 0.008, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[-0.001, -0.002, -0.001]}
            />
            <mesh
              name="rim002"
              castShadow
              receiveShadow
              geometry={nodes.rim002.geometry}
              material={materials["glossy black.001"]}
              position={[-0.035, 0.007, 0]}
              rotation={[0.033, 1.571, 0]}
              scale={-0.005}
            />
            <mesh
              name="rim003"
              castShadow
              receiveShadow
              geometry={nodes.rim003.geometry}
              material={materials["glossy black.001"]}
              position={[-0.012, 0.007, 0]}
              rotation={[0.033, 1.571, 0]}
              scale={-0.005}
            />
            <mesh
              name="rim004"
              castShadow
              receiveShadow
              geometry={nodes.rim004.geometry}
              material={materials["glossy black.001"]}
              position={[-0.035, 0.007, 0]}
              rotation={[0.033, 1.571, 0]}
              scale={-0.005}
            />
          </group>
          <group
            name="Empty005"
            position={[0.194, 0.078, 0.333]}
            rotation={[-Math.PI, 0.611, 0]}
            scale={[-0.294, -0.338, -0.338]}
          >
            <mesh
              name="brake003"
              castShadow
              receiveShadow
              geometry={nodes.brake003.geometry}
              material={materials["brake.002"]}
              position={[0.031, 0, -0.077]}
              scale={[0.741, 0.697, 0.72]}
            />
            <mesh
              name="brake004"
              castShadow
              receiveShadow
              geometry={nodes.brake004.geometry}
              material={materials["Material.003"]}
              position={[0.025, 0, 0.008]}
              scale={[0.741, 0.72, 0.72]}
            />
            <group
              name="Plane055"
              position={[0, 0.007, 0]}
              rotation={[0, 0, 0.178]}
              scale={[0.491, 0.625, 0.623]}
            >
              <mesh
                name="Plane049_1"
                castShadow
                receiveShadow
                geometry={nodes.Plane049_1.geometry}
                material={materials["Front Tire.003"]}
              />
              <mesh
                name="Plane049_2"
                castShadow
                receiveShadow
                geometry={nodes.Plane049_2.geometry}
                material={materials["Front Tire.002"]}
              />
            </group>
            <mesh
              name="Plane058"
              castShadow
              receiveShadow
              geometry={nodes.Plane058.geometry}
              material={materials.chrome}
              position={[-0.037, 0.008, 0]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
              scale={[-0.001, -0.002, -0.001]}
            />
            <mesh
              name="rim001"
              castShadow
              receiveShadow
              geometry={nodes.rim001.geometry}
              material={materials["glossy black.001"]}
              position={[-0.035, 0.007, 0]}
              rotation={[0.033, 1.571, 0]}
              scale={-0.005}
            />
            <mesh
              name="rim007"
              castShadow
              receiveShadow
              geometry={nodes.rim007.geometry}
              material={materials["glossy black.001"]}
              position={[-0.035, 0.007, 0]}
              rotation={[0.033, 1.571, 0]}
              scale={-0.005}
            />
            <mesh
              name="rim010"
              castShadow
              receiveShadow
              geometry={nodes.rim010.geometry}
              material={materials["glossy black.001"]}
              position={[-0.012, 0.007, 0]}
              rotation={[0.033, 1.571, 0]}
              scale={-0.005}
            />
          </group>
          <group
            name="mirror"
            position={[0, 0, -0.033]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={0.357}
          >
            <mesh
              name="1004"
              castShadow
              receiveShadow
              geometry={nodes["1004"].geometry}
              material={materials["glossy black"]}
            />
            <mesh
              name="1004_1"
              castShadow
              receiveShadow
              geometry={nodes["1004_1"].geometry}
              material={materials.chrome}
            />
            <mesh
              name="1004_2"
              castShadow
              receiveShadow
              geometry={nodes["1004_2"].geometry}
              material={materials["glass.001"]}
            />
          </group>
          <mesh
            name="Plane"
            castShadow
            receiveShadow
            geometry={nodes.Plane.geometry}
            material={materials["body.002"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane001"
            castShadow
            receiveShadow
            geometry={nodes.Plane001.geometry}
            material={materials.grill}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.009}
          />
          <mesh
            name="Plane002"
            castShadow
            receiveShadow
            geometry={nodes.Plane002.geometry}
            material={materials["headlight.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane003"
            castShadow
            receiveShadow
            geometry={nodes.Plane003.geometry}
            material={materials["headlight.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane004"
            castShadow
            receiveShadow
            geometry={nodes.Plane004.geometry}
            material={materials.headlight}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane005"
            castShadow
            receiveShadow
            geometry={nodes.Plane005.geometry}
            material={materials["headlight.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane006"
            castShadow
            receiveShadow
            geometry={nodes.Plane006.geometry}
            material={materials["headlight.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane007"
            castShadow
            receiveShadow
            geometry={nodes.Plane007.geometry}
            material={materials["headlight.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <group
            name="Plane008"
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          >
            <mesh
              name="Plane010_1"
              castShadow
              receiveShadow
              geometry={nodes.Plane010_1.geometry}
              material={materials.grill}
            />
            <mesh
              name="Plane010_2"
              castShadow
              receiveShadow
              geometry={nodes.Plane010_2.geometry}
              material={materials["headlight.001"]}
            />
          </group>
          <mesh
            name="Plane009"
            castShadow
            receiveShadow
            geometry={nodes.Plane009.geometry}
            material={materials["body.002"]}
            position={[-0.001, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane010"
            castShadow
            receiveShadow
            geometry={nodes.Plane010.geometry}
            material={materials["body.002"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane011"
            castShadow
            receiveShadow
            geometry={nodes.Plane011.geometry}
            material={materials["body.002"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane012"
            castShadow
            receiveShadow
            geometry={nodes.Plane012.geometry}
            material={materials.glass}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane013"
            castShadow
            receiveShadow
            geometry={nodes.Plane013.geometry}
            material={materials["body.002"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane014"
            castShadow
            receiveShadow
            geometry={nodes.Plane014.geometry}
            material={materials["body.002"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane016"
            castShadow
            receiveShadow
            geometry={nodes.Plane016.geometry}
            material={materials["body.002"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane017"
            castShadow
            receiveShadow
            geometry={nodes.Plane017.geometry}
            material={materials["body.002"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane018"
            castShadow
            receiveShadow
            geometry={nodes.Plane018.geometry}
            material={materials["body.002"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane019"
            castShadow
            receiveShadow
            geometry={nodes.Plane019.geometry}
            material={materials.grill}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane020"
            castShadow
            receiveShadow
            geometry={nodes.Plane020.geometry}
            material={materials["headlight.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane021"
            castShadow
            receiveShadow
            geometry={nodes.Plane021.geometry}
            material={materials["headlight.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane022"
            castShadow
            receiveShadow
            geometry={nodes.Plane022.geometry}
            material={materials["glossy black"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane023"
            castShadow
            receiveShadow
            geometry={nodes.Plane023.geometry}
            material={materials["headlight.001"]}
            position={[0, 0, 0.744]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.357}
          />
          <mesh
            name="Plane024"
            castShadow
            receiveShadow
            geometry={nodes.Plane024.geometry}
            material={materials["headlight.001"]}
            position={[0, 0, -0.667]}
            rotation={[Math.PI / 2, 0, Math.PI]}
            scale={0.028}
          />
          <mesh
            name="Plane025"
            castShadow
            receiveShadow
            geometry={nodes.Plane025.geometry}
            material={materials["headlight.001"]}
            position={[0, 0, -0.265]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane026"
            castShadow
            receiveShadow
            geometry={nodes.Plane026.geometry}
            material={materials["headlight.001"]}
            position={[0, 0, -0.265]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane027"
            castShadow
            receiveShadow
            geometry={nodes.Plane027.geometry}
            material={materials["headlight.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane028"
            castShadow
            receiveShadow
            geometry={nodes.Plane028.geometry}
            material={materials["glass.002"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane029"
            castShadow
            receiveShadow
            geometry={nodes.Plane029.geometry}
            material={materials["headlight.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane030"
            castShadow
            receiveShadow
            geometry={nodes.Plane030.geometry}
            material={materials["headlight.001"]}
            position={[0, 0, 0.744]}
            scale={0.028}
          />
          <mesh
            name="Plane031"
            castShadow
            receiveShadow
            geometry={nodes.Plane031.geometry}
            material={materials["body.002"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane032"
            castShadow
            receiveShadow
            geometry={nodes.Plane032.geometry}
            material={materials["headlight.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane033"
            castShadow
            receiveShadow
            geometry={nodes.Plane033.geometry}
            material={materials["body.002"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane034"
            castShadow
            receiveShadow
            geometry={nodes.Plane034.geometry}
            material={materials["glass.002"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane035"
            castShadow
            receiveShadow
            geometry={nodes.Plane035.geometry}
            material={materials["glass.002"]}
            position={[0, 0, 0.077]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.357}
          />
          <mesh
            name="Plane036"
            castShadow
            receiveShadow
            geometry={nodes.Plane036.geometry}
            material={materials.grill}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane037"
            castShadow
            receiveShadow
            geometry={nodes.Plane037.geometry}
            material={materials["headlight.001"]}
            position={[0, 0, 0.744]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.357}
          />
          <mesh
            name="Plane038"
            castShadow
            receiveShadow
            geometry={nodes.Plane038.geometry}
            material={materials["headlight.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane039"
            castShadow
            receiveShadow
            geometry={nodes.Plane039.geometry}
            material={materials["mat mt"]}
            position={[0, 0.09, 0]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane040"
            castShadow
            receiveShadow
            geometry={nodes.Plane040.geometry}
            material={materials["mat mt"]}
            position={[0, 0, 0.744]}
            scale={0.357}
          />
          <mesh
            name="Plane041"
            castShadow
            receiveShadow
            geometry={nodes.Plane041.geometry}
            material={materials["mat mt"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane042"
            castShadow
            receiveShadow
            geometry={nodes.Plane042.geometry}
            material={materials["glossy black"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane043"
            castShadow
            receiveShadow
            geometry={nodes.Plane043.geometry}
            material={materials["mat mt.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane044"
            castShadow
            receiveShadow
            geometry={nodes.Plane044.geometry}
            material={materials["mat mt"]}
            position={[0, 0, 0.744]}
            scale={0.357}
          />
          <mesh
            name="Plane045"
            castShadow
            receiveShadow
            geometry={nodes.Plane045.geometry}
            material={materials["headlight.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane046"
            castShadow
            receiveShadow
            geometry={nodes.Plane046.geometry}
            material={materials["mat mt.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane047"
            castShadow
            receiveShadow
            geometry={nodes.Plane047.geometry}
            material={materials["glass.002"]}
            position={[0, 0, 0.744]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.357}
          />
          <mesh
            name="Plane048"
            castShadow
            receiveShadow
            geometry={nodes.Plane048.geometry}
            material={materials["mat mt.001"]}
            position={[0, 0, 0.744]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.357}
          />
          <mesh
            name="Plane049"
            castShadow
            receiveShadow
            geometry={nodes.Plane049.geometry}
            material={materials["headlight.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane050"
            castShadow
            receiveShadow
            geometry={nodes.Plane050.geometry}
            material={materials["mat mt.001"]}
            position={[-0.001, 0, 0.744]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.357}
          />
          <mesh
            name="Plane051"
            castShadow
            receiveShadow
            geometry={nodes.Plane051.geometry}
            material={materials["mat mt.001"]}
            position={[0, 0, 0.077]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.357}
          />
          <mesh
            name="Plane052"
            castShadow
            receiveShadow
            geometry={nodes.Plane052.geometry}
            material={materials["mat mt.001"]}
            position={[0, 0, 0.077]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.357}
          />
          <group
            name="Plane053"
            position={[0, 0.147, 0.554]}
            rotation={[0.515, 0, 0]}
            scale={0.001}
          >
            <mesh
              name="Mesh_31"
              castShadow
              receiveShadow
              geometry={nodes.Mesh_31.geometry}
              material={materials.chrome}
            />
            <mesh
              name="Mesh_32"
              castShadow
              receiveShadow
              geometry={nodes.Mesh_32.geometry}
              material={materials["glossy black"]}
            />
          </group>
          <group
            name="Plane054"
            position={[0, 0.21, -0.467]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={0.001}
          >
            <mesh
              name="Mesh_33"
              castShadow
              receiveShadow
              geometry={nodes.Mesh_33.geometry}
              material={materials.chrome}
            />
            <mesh
              name="Mesh_34"
              castShadow
              receiveShadow
              geometry={nodes.Mesh_34.geometry}
              material={materials["glossy black"]}
            />
          </group>
          <mesh
            name="Plane056"
            castShadow
            receiveShadow
            geometry={nodes.Plane056.geometry}
            material={materials["headlight.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <mesh
            name="Plane057"
            castShadow
            receiveShadow
            geometry={nodes.Plane057.geometry}
            material={materials["mat mt.001"]}
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          />
          <group
            name="Plane061"
            position={[0.194, 0.08, -0.264]}
            rotation={[-Math.PI, 0, 0.176]}
            scale={[-0.145, -0.21, -0.21]}
          >
            <mesh
              name="Plane062_1"
              castShadow
              receiveShadow
              geometry={nodes.Plane062_1.geometry}
              material={materials["Front Tire.003"]}
            />
            <mesh
              name="Plane062_2"
              castShadow
              receiveShadow
              geometry={nodes.Plane062_2.geometry}
              material={materials["Front Tire.002"]}
            />
          </group>
          <mesh
            name="Plane062"
            castShadow
            receiveShadow
            geometry={nodes.Plane062.geometry}
            material={materials.chrome}
            position={[0.205, 0.081, -0.264]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={0}
          />
          <group
            name="Plane063"
            position={[-0.196, 0.08, -0.264]}
            rotation={[0, 0, 0.176]}
            scale={[0.145, 0.21, 0.21]}
          >
            <mesh
              name="Plane064_1"
              castShadow
              receiveShadow
              geometry={nodes.Plane064_1.geometry}
              material={materials["Front Tire.003"]}
            />
            <mesh
              name="Plane064_2"
              castShadow
              receiveShadow
              geometry={nodes.Plane064_2.geometry}
              material={materials["Front Tire.002"]}
            />
          </group>
          <mesh
            name="Plane064"
            castShadow
            receiveShadow
            geometry={nodes.Plane064.geometry}
            material={materials.chrome}
            position={[-0.207, 0.081, -0.264]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={0}
          />
          <group
            name="Plane065"
            position={[0, 0.131, 0.564]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          >
            <mesh
              name="Plane066_1"
              castShadow
              receiveShadow
              geometry={nodes.Plane066_1.geometry}
              material={materials["mat mt.001"]}
            />
            <mesh
              name="Plane066_2"
              castShadow
              receiveShadow
              geometry={nodes.Plane066_2.geometry}
              material={materials["tailight.004"]}
            />
          </group>
          <group
            name="Plane066"
            position={[-0.001, 0.115, 0.568]}
            rotation={[1.663, 0, Math.PI]}
            scale={[0.228, 0.201, 0.201]}
          >
            <mesh
              name="Plane067_1"
              castShadow
              receiveShadow
              geometry={nodes.Plane067_1.geometry}
              material={materials.white}
            />
            <mesh
              name="Plane067_2"
              castShadow
              receiveShadow
              geometry={nodes.Plane067_2.geometry}
              material={materials["glossy black.004"]}
            />
          </group>
          <group
            name="Plane067"
            position={[-0.001, 0.146, -0.461]}
            rotation={[1.524, 0, 0]}
            scale={[0.228, 0.201, 0.201]}
          >
            <mesh
              name="Plane068_1"
              castShadow
              receiveShadow
              geometry={nodes.Plane068_1.geometry}
              material={materials.white}
            />
            <mesh
              name="Plane068_2"
              castShadow
              receiveShadow
              geometry={nodes.Plane068_2.geometry}
              material={materials["glossy black.004"]}
            />
          </group>
          <group
            name="Plane068"
            position={[0, 0.131, 0.566]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.357}
          >
            <mesh
              name="Plane056_1"
              castShadow
              receiveShadow
              geometry={nodes.Plane056_1.geometry}
              material={materials["headlight.001"]}
            />
            <mesh
              name="Plane056_2"
              castShadow
              receiveShadow
              geometry={nodes.Plane056_2.geometry}
              material={materials["tailight.005"]}
            />
          </group>
          <mesh
            name="rim005"
            castShadow
            receiveShadow
            geometry={nodes.rim005.geometry}
            material={materials["glossy black.001"]}
            position={[0.204, 0.08, -0.264]}
            rotation={[-3.108, 1.571, 0]}
            scale={[0.002, 0.002, 0.001]}
          />
          <mesh
            name="rim006"
            castShadow
            receiveShadow
            geometry={nodes.rim006.geometry}
            material={materials["glossy black.001"]}
            position={[0.198, 0.08, -0.264]}
            rotation={[-3.108, 1.571, 0]}
            scale={[0.002, 0.002, 0.001]}
          />
          <mesh
            name="rim008"
            castShadow
            receiveShadow
            geometry={nodes.rim008.geometry}
            material={materials["glossy black.001"]}
            position={[0.204, 0.08, -0.264]}
            rotation={[-3.108, 1.571, 0]}
            scale={[0.002, 0.002, 0.001]}
          />
          <mesh
            name="rim009"
            castShadow
            receiveShadow
            geometry={nodes.rim009.geometry}
            material={materials["glossy black.001"]}
            position={[-0.206, 0.08, -0.264]}
            rotation={[0.033, 1.571, 0]}
            scale={[-0.002, -0.002, -0.001]}
          />
          <mesh
            name="rim011"
            castShadow
            receiveShadow
            geometry={nodes.rim011.geometry}
            material={materials["glossy black.001"]}
            position={[-0.199, 0.08, -0.264]}
            rotation={[0.033, 1.571, 0]}
            scale={[-0.002, -0.002, -0.001]}
          />
          <mesh
            name="rim012"
            castShadow
            receiveShadow
            geometry={nodes.rim012.geometry}
            material={materials["glossy black.001"]}
            position={[-0.206, 0.08, -0.264]}
            rotation={[0.033, 1.571, 0]}
            scale={[-0.002, -0.002, -0.001]}
          />
          <mesh
            name="sit"
            castShadow
            receiveShadow
            geometry={nodes.sit.geometry}
            material={materials["Mat mt.001"]}
            position={[-0.003, 0.145, -0.048]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={0}
          />
          <mesh
            name="steer"
            castShadow
            receiveShadow
            geometry={nodes.steer.geometry}
            material={materials["Mat mt.001"]}
            position={[0.052, 0.195, 0.036]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={0}
          />
          <mesh
            name="taillight"
            castShadow
            receiveShadow
            geometry={nodes.taillight.geometry}
            material={materials.tailight}
            position={[0, 0, 0.744]}
            rotation={[0, 0, Math.PI]}
            scale={[-0.172, -0.187, -0.199]}
          />
          <group
            name="taillight001"
            position={[0, 0, 0.744]}
            rotation={[0, 0, Math.PI]}
            scale={[-0.172, -0.187, -0.199]}
          >
            <mesh
              name="1001_1"
              castShadow
              receiveShadow
              geometry={nodes["1001_1"].geometry}
              material={materials["tailight.001"]}
            />
            <mesh
              name="1001_2"
              castShadow
              receiveShadow
              geometry={nodes["1001_2"].geometry}
              material={materials["tailight.003"]}
            />
            <mesh
              name="1001_3"
              castShadow
              receiveShadow
              geometry={nodes["1001_3"].geometry}
              material={materials["tailight.005"]}
            />
          </group>
          <mesh
            name="taillight002"
            castShadow
            receiveShadow
            geometry={nodes.taillight002.geometry}
            material={materials.tailight}
            position={[0, 0, 0.744]}
            rotation={[0, 0, Math.PI]}
            scale={[-0.172, -0.187, -0.199]}
          />
          <mesh
            name="taillight003"
            castShadow
            receiveShadow
            geometry={nodes.taillight003.geometry}
            material={materials.glass}
            position={[0, 0, 0.744]}
            rotation={[-Math.PI / 2, 0, -Math.PI]}
            scale={[-0.172, -0.187, -0.199]}
          />
          <mesh
            name="text"
            castShadow
            receiveShadow
            geometry={nodes.text.geometry}
            material={materials["glossy black"]}
            position={[0, 0.181, -0.472]}
            rotation={[-1.118, 0, 0]}
            scale={-0.309}
          />
          <mesh
            name="Text"
            castShadow
            receiveShadow
            geometry={nodes.Text.geometry}
            material={materials.chrome}
            position={[0, 0.187, -0.47]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={0.005}
          />
          <mesh
            name="Text001"
            castShadow
            receiveShadow
            geometry={nodes.Text001.geometry}
            material={materials["glossy black.004"]}
            position={[-0.001, 0.115, 0.568]}
            rotation={[1.664, 0, 0]}
            scale={0.02}
          />
          <mesh
            name="text001"
            castShadow
            receiveShadow
            geometry={nodes.text001.geometry}
            material={materials.chrome}
            position={[0, 0.181, -0.472]}
            rotation={[2.024, 0, 0]}
            scale={0.374}
          />
          <mesh
            name="Text002"
            castShadow
            receiveShadow
            geometry={nodes.Text002.geometry}
            material={materials["glossy black.004"]}
            position={[-0.001, 0.146, -0.46]}
            rotation={[1.524, 0, Math.PI]}
            scale={0.02}
          />
          <mesh
            name="text002"
            castShadow
            receiveShadow
            geometry={nodes.text002.geometry}
            material={materials.chrome}
            position={[0, 0.181, -0.472]}
            rotation={[-1.118, 0, 0]}
            scale={-0.309}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/toyota.glb");
